### ISSUE TITLE
Different host for repository and issues

### ISSUE THREAD

**Issue by sadiqkhoja** [stevemao/conventional-commits-writer#18]
Is it possible to have different host for repository(git) and issues tracking? so that link to commit number points to repository host and "closes" points to issue tracking host. I am using bitbucket as repository and JIRA as issue tracking.

**Comment by stevemao** [comment]
Not really...

**Comment by stevemao** [comment]
https://github.com/ajoslin/conventional-changelog/issues/128

**Comment by stevemao** [comment]
I think I'm wrong. Using bugs url in the package.json should be already possible. the [package.json value is attached to the context](https://github.com/stevemao/conventional-changelog-core#packagedata) and you just need to customise your template. Let me know if you can't achieve this @sadiqkhoja
