### ISSUE TITLE
h2 for pre release?

### ISSUE THREAD

**Issue by e-cloud** [stevemao/conventional-commits-writer#23]
now, only patches have `h2` as header size, but in common cases it better to use `h2` for pre releases

**Comment by stevemao** [comment]
You can always write your own templates.

**Comment by e-cloud** [comment]
But this is one base library which i track down from standard-version, i guess there is no way that i can modify anything from standard-version

**Comment by stevemao** [comment]
cc @bcoe @Tapppi What do you think?

**Comment by Tapppi** [comment]
Yes IMHO all but major and minor releases should probably be `h2`. Whether you want to do another option `isPrerelease` or incorporate it into `isPatch`'s default doesn't matter to me much.

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
