### ISSUE TITLE
Allow version to be passed in asynchronously

### ISSUE THREAD

**Issue by gpleiss** [stevemao/conventional-commits-writer#6]
Hello,

We are using `conventional-changelog` to generate a changelog for our release. Our release flow is something along the lines of:
- Figure out the release version
- Generate the changelog
- (some other stuff)
- Make a commit with the bumped version number and the generated changelog

We are using gulp to generate our changelog:

``` js
gulp.task('release-generate-changelog', () => {
  const newChangesStream = changelog(
    {preset: 'angular', warn: log, append: true},
    {version: <VERSION>},
    {},
    {noteKeywords: ['BREAKING CHANGE', 'DEPRECATION WARNING']},
    {transform: commitTransform}
  );

  const oldChangesStream = gulp.src('CHANGELOG.md')
    .pipe(map((file, cb) => cb(null, file.contents)));

  const latestChangesFileStream = newChangesStream
    .pipe(source('LATEST_CHANGES.md'));

  const changelogFileStream = series(newChangesStream, oldChangesStream)
    .pipe(source('CHANGELOG.md'));

  return merge(changelogFileStream, latestChangesFileStream)
    .pipe(gulp.dest('.'));
});
```

We want to get `<VERSION>` by using `conventional-recommended-bump`. However, conventional-recommended-bump works asynchronously, and `conventional-commits-writer` expects version to be passed in synchronously.

Is there some way we can give `conventional-commits-writer` the version asynchronously? Maybe the `version` option could accept a promise?

Thanks!

cc/ @stubbornella @matt-royal

**Comment by stevemao** [comment]
There are several ways to do it and this is out of the scope of this module. promise is one of them. the crux of it is to get the version and save it somewhere then pass it to the writer. Maybe use https://github.com/OverZealous/run-sequence

Note that for the use of gulp we need a gulp plugin because conventional-changelog doesn't handle files so we need vinyl to do it for us. Looks like people really want it to work with gulp so once I solve all the known bugs I'll make the gulp plugin.

**Comment by gpleiss** [comment]
Given the push to make `conventional-changelog` stream based (which I am a huge fan of by the way, thanks for all your work on this!), it would be nice if the `conventional-recommended-bump` could fit nicely into this stream flow as well.

`run-sequence` will work. However, it's cumbersome because this adds a strict order dependence on our gulp tasks.

Say our gulp workflow looked like:

``` js
gulp.task('release-bump-version', (done) =>
  /* run `conventional-recommended-bump` and update package.json with the new version number */
);

gulp.task('release-generate-changelog', ['release-bump-version'], (done) =>
  const newChangesStream = changelog(
    {preset: 'angular', warn: log, append: true},
    {version: JSON.parse(fs.readSync('./package.json'))},
    {},
    {noteKeywords: ['BREAKING CHANGE', 'DEPRECATION WARNING']},
    {transform: commitTransform}
  );

  /* ... */
);
```

I find this to be a little brittle and ugly. There's a hidden dependency that the version is written to disk in the package.json (which is not too hard to uncover, but is not as clear as passing something around in memory). Now the tasks are order-dependent, when really they are accomplishing two independent tasks. So we're making the code a bit more tangled.

If we submitted a pull request to allow version to be passed as a promise, would you be open to accepting it after a review?

**Comment by stevemao** [comment]
I think the code you wrote is actually very good... As the recommended workflow is

```
Make changes
Commit those changes
Bump (increase version in package.json)
conventional-changelog
Commit (chore: release...)
Tag (v1.0.0)
```

Why do you think the version in package.json shouldn't be changed before `conventional-changelog` task? Also to make `conventional-recomended-bump` return a promise, all you need to do is to use `Q.nfcall` or `Q.denodeify` so is it necessary to add it into the module? 

`conventional-changelog` should auto read the package.json (this could be documented better) so you don't have to pass the version manually.

**Comment by gpleiss** [comment]
Ok, we'll try what you've suggested and see how it goes. Thanks for your help!
